//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetCore.API.Example.Service
{
    /*
  * This class is used to show sample Proxy layer example
  * To Do: For Actual project please remove this file 
  * after getting the idea of how to implement.
  */
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookingForGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/DotNetCore.API.Example.Service")]
    public partial class LookingForGroupRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.Guid> AppTokenField;
        
        private bool IsApprovedField;
        
        private int UserIdField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> AppToken
        {
            get
            {
                return this.AppTokenField;
            }
            set
            {
                this.AppTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved
        {
            get
            {
                return this.IsApprovedField;
            }
            set
            {
                this.IsApprovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookingForGroupResponse", Namespace="http://schemas.datacontract.org/2004/07/DotNetCore.API.Example.Service")]
    public partial class LookingForGroupResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.DotNetCore.API.com/example/service/", ConfigurationName="IWcfService")]
public interface IWcfService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldSoapResponse")]
    string HelloWorldSoap();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldSoapResponse")]
    System.Threading.Tasks.Task<string> HelloWorldSoapAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldRestResponse")]
    string HelloWorldRest();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/HelloWorldRestResponse")]
    System.Threading.Tasks.Task<string> HelloWorldRestAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeSoapResponse")]
    string WelcomeHomeSoap(string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeSoapResponse")]
    System.Threading.Tasks.Task<string> WelcomeHomeSoapAsync(string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeRestResponse")]
    string WelcomeHomeRest(string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/WelcomeHomeRestResponse")]
    System.Threading.Tasks.Task<string> WelcomeHomeRestAsync(string type);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupSoapResponse")]
    DotNetCore.API.Example.Service.LookingForGroupResponse LookingForGroupSoap(DotNetCore.API.Example.Service.LookingForGroupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupSoap", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupSoapResponse")]
    System.Threading.Tasks.Task<DotNetCore.API.Example.Service.LookingForGroupResponse> LookingForGroupSoapAsync(DotNetCore.API.Example.Service.LookingForGroupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupRestResponse")]
    DotNetCore.API.Example.Service.LookingForGroupResponse LookingForGroupRest(DotNetCore.API.Example.Service.LookingForGroupRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupRest", ReplyAction="http://www.DotNetCore.API.com/example/service/IWcfService/LookingForGroupRestResponse")]
    System.Threading.Tasks.Task<DotNetCore.API.Example.Service.LookingForGroupResponse> LookingForGroupRestAsync(DotNetCore.API.Example.Service.LookingForGroupRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IWcfServiceChannel : IWcfService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class WcfServiceClient : System.ServiceModel.ClientBase<IWcfService>, IWcfService
{
    
    public WcfServiceClient()
    {
    }
    
    public WcfServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string HelloWorldSoap()
    {
        return base.Channel.HelloWorldSoap();
    }
    
    public System.Threading.Tasks.Task<string> HelloWorldSoapAsync()
    {
        return base.Channel.HelloWorldSoapAsync();
    }
    
    public string HelloWorldRest()
    {
        return base.Channel.HelloWorldRest();
    }
    
    public System.Threading.Tasks.Task<string> HelloWorldRestAsync()
    {
        return base.Channel.HelloWorldRestAsync();
    }
    
    public string WelcomeHomeSoap(string type)
    {
        return base.Channel.WelcomeHomeSoap(type);
    }
    
    public System.Threading.Tasks.Task<string> WelcomeHomeSoapAsync(string type)
    {
        return base.Channel.WelcomeHomeSoapAsync(type);
    }
    
    public string WelcomeHomeRest(string type)
    {
        return base.Channel.WelcomeHomeRest(type);
    }
    
    public System.Threading.Tasks.Task<string> WelcomeHomeRestAsync(string type)
    {
        return base.Channel.WelcomeHomeRestAsync(type);
    }
    
    public DotNetCore.API.Example.Service.LookingForGroupResponse LookingForGroupSoap(DotNetCore.API.Example.Service.LookingForGroupRequest request)
    {
        return base.Channel.LookingForGroupSoap(request);
    }
    
    public System.Threading.Tasks.Task<DotNetCore.API.Example.Service.LookingForGroupResponse> LookingForGroupSoapAsync(DotNetCore.API.Example.Service.LookingForGroupRequest request)
    {
        return base.Channel.LookingForGroupSoapAsync(request);
    }
    
    public DotNetCore.API.Example.Service.LookingForGroupResponse LookingForGroupRest(DotNetCore.API.Example.Service.LookingForGroupRequest request)
    {
        return base.Channel.LookingForGroupRest(request);
    }
    
    public System.Threading.Tasks.Task<DotNetCore.API.Example.Service.LookingForGroupResponse> LookingForGroupRestAsync(DotNetCore.API.Example.Service.LookingForGroupRequest request)
    {
        return base.Channel.LookingForGroupRestAsync(request);
    }
}
